import type { Metadata } from "next";
import ReactQueryProvider from "../utils/providers/ReactQueryProvider";
import "./globals.css";
import {worksans, nunito} from './fonts'
import { ThemeProvider } from '@mui/material';
import theme from "./lib/theme";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} ${worksans.variable}`}>
        <ReactQueryProvider>
          <ThemeProvider theme={theme}>
              <main>{children}</main>
          </ThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
