import type { Metadata } from "next";
import ReactQueryProvider from "../utils/providers/ReactQueryProvider";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import "./globals.css";
import theme from "@/style/theme";
import { ThemeProvider } from "@mui/material/styles";
import { worksans, nunitosans } from "@/style/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${worksans.variable} ${nunitosans.variable}`}>
        <ReactQueryProvider>
<<<<<<< Updated upstream
=======
          <CssBaseline />
>>>>>>> Stashed changes
          <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
              <main>{children}</main>
            </ThemeProvider>
          </AppRouterCacheProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
