/**
 * Calls the `/api/ia/generate-description` endpoint to generate
 * an AI-powered product description for a given product name.
 *
 * @async
 * @function generateDescription
 * @param {string} name - The product name to generate a description for.
 *
 * @returns {Promise<string>} A concise product description string generated by the AI.
 *
 * @throws {Error} If the API request fails or returns a non-OK response.
 *
 */

export async function generateDescription(name: string): Promise<string> {
  const res = await fetch("/api/ia/generate-description", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ name }),
  });

  if (!res.ok) {
    throw new Error("Failed to generate description");
  }

  const data = await res.json();
  return data.description || "";
}
