name: Run Lint, Build, Tests and Enforce Coverage

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      USER_EMAIL: ${{ secrets.USER_EMAIL }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.18.0"

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint -- --max-warnings=0

      - name: Build app
        run: npm run build

      - name: Run tests (with coverage enforcement)
        run: npm test

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

      - name: Start application in background
        run: npm run start &

      - name: Wait until app is ready
        run: npx wait-on http://localhost:3000

      - name: Run Cypress E2E tests
        run: npx cypress run
